### ISSUE TITLE
UVL splits features with a space into two features

### ISSUE THREAD

**Issue by Rahel12342** [FeatureIDE/FeatureIDE#1143] opened 2021-07-13 18:55 UTC
#### Prerequisitives
* **Eclipse Version:**  `2020-03 (4.15.0)`
* **FeatureIDE-Version:**  `3.7`
* **Operating system:** `Windows 10`
* **Java runtime used to run eclipse:** `jdk-14.0.1`

### Issue description
When having a feature with a space and its name and a constraint including the feature it looks like in the first picture. When saving and closing the editor and then open the moodel again, it looks like in the second picture. The feature is split into several different features by the space and the same happens with the constraint.

![image](https://user-images.githubusercontent.com/64740628/125508947-1371c050-f095-404d-94ca-39865c71d85b.png)

![image](https://user-images.githubusercontent.com/64740628/125508998-db3e2619-4097-4d9a-9494-85c27b5af9b5.png)

**Comment by michaelsoft-binbows** [comment] 2021-08-02 11:48
After trying to reproduce this behaviour, the contraint `Windows ⇒ To file` disappeared.

**Comment by Rahel12342** [comment] 2021-08-02 12:49
@michaelsoft-binbows yes that happens when having a composed uvl model. That is a common issue happening with the constraints and should be reported as an issue itself.

**Comment by johannesherschel** [comment] 2021-08-04 14:49
There are also similar issues with other names edited in the diagram. If a feature name which is invalid in UVL is entered in the diagram, e.g. a name starting with a digit or containing special characters like - or #, the feature model in the diagram continues to work. But after closing and reopening the model, it opens in the Source tab of the editor and reports a parse error because of the invalid feature name, and the diagram is inaccessible (as it should be).
Such feature names should probably be disallowed when editing a UVL model via the diagram, similar to how duplicate names are disallowed.

**Comment by michaelsoft-binbows** [comment] 2021-08-20 15:40
When renaming features in the feature model editor and switching to the "Source" tab, the feature diagram cannot be opened if the given name is illegal.
Legal names are only [A-Za-z]([A-Za-z0-9])*

**Comment by michaelsoft-binbows** [comment] 2021-09-03 17:08
Progress:
1. When trying to rename a feature, a valid feature name now has to match [a-zA-Z][\w\+\ ]*
    Before, only . (dot), ( and ) (left & right paranthesis) were prohibited to be used.
    The regular expression has been adjusted according to <https://github.com/michaelsoft-binbows/uvl-parser/blob/master/resources/uvl.bnf> and <https://github.com/diverso-lab/uvl-diverso/blob/master/UVL.g4>. 
2. The uvl parser now supports only valid feature names as specified above. Features names containing spaces must be encapsulated by quotations "".

Changes that still need to be done:
1. Correctly saving feature names which contain whites spaces with quotations.
1. Read feature names from the uvl file correctly.

**Comment by michaelsoft-binbows** [comment] 2021-09-03 17:46
> The feature model editor already checks for valid names but it seems that it does not know the valid names for UVL models yet. Have a look at AHEAD or FeatureHouse examples and try to enter names with whitespaces. A conceptual difference is that the constraints on the names are given by composers in these cases and I'm not sure whether a feature model format can also specify valid names independently of that.

If the feature name nomenclature is determined by the composer, how is it possible for parsers to parse that? Not at all, i.e., match any character? However, the regex for composed feature names is hard coded by `^[a-zA-Z]+\\w*$` in class `FMComposerExtension`. How is the feature name pattern altered by given composers? Please tell me if I am wrong.

**Comment by michaelsoft-binbows** [comment] 2021-09-15 13:05
Issue has been completed. Now, it is possible to name features using white spaces. If a feature name contains white spaces, the feature is surrounded with quotation marks. Also, further characters are now allowed to be used in feature names, that are `+` and `_`. From now on, a feature name saved in the UVL format has to match `[a-zA-Z][a-zA-Z0-9_\+\ ]*`. For additional information, please refer to the commit messages.

Remark: The grammar of the UVL parser has been altered to meet the new requirements. A newly built jar file has been added to one of the commits concerning this issue.

**Closed** 2021-11-30 14:12 UTC
Labels: bug (minor), Feature Modeling, UVL
