### ISSUE TITLE
Undoing "collapse siblings" throws exception

### ISSUE THREAD

**Issue by TimoGuenther** [FeatureIDE/FeatureIDE#447] opened 2016-11-15 18:33 UTC
Steps to reproduce:
1. Create a feature model containing a feature with siblings.
2. Collapse the siblings of the feature using the "collapse siblings" context menu entry.
3. Undo the operation (Ctrl-Z).

Example:
![collapse children undo exception](https://cloud.githubusercontent.com/assets/18397625/20317978/aceb21c2-ab68-11e6-91d8-0c279deb0625.png)

Only the undo operation is affected. Effectively undoing the operation by expanding each sibling or expanding everything is not affected.

**Comment by Subaro** [comment] 2016-11-16 12:25
The issue is now fixed on the bs_team1 branch.

**Closed** 2016-11-16 12:48 UTC
Labels: bug (major), Feature Modeling
