### ISSUE TITLE
Product generation with CASA does not work

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#414] opened 2016-09-08 19:26 UTC
Tried it several times with different values for T, but nothing happens. Folder for products is generated and then it seems to be finished.

**Comment by jabiercoding** [comment] 2016-10-02 20:17
This seems to be a duplicate of issue #387

**Comment by jabiercoding** [comment] 2016-10-04 17:44
I copy/paste here the debug information from the closed issue.
`de.ovgu.featureide.ui.actions.generator.configuration.SPLCAToolConfigurationGenerator.runSPLCATool() `calls `generate(100, maxConfigs());` which is an empty method in `no.sintef.ict.splcatool.CoveringArrayCASA`

**Comment by tthuem** [comment] 2016-10-04 17:48
Thanks Jabier!

**Comment by tthuem** [comment] 2016-10-04 17:50
@Alhajjaji Mustafa, can you add some instructions on what we need to install to make it work? Ideally, those instructions are visible whenever CASA is selected/chosen.

**Comment by skrieter** [comment] 2016-10-14 23:37
I fixed the CASA dependency problems in a072b2f07e372d69dab5e344433f20deb49ac4bc.
However, CASA is still unlikley to work on most machines as it misses a c++ library (libstdc++-6.dll).

The correct version of this library must be availble on the system in order for CASA to work.
Furthermore, the current version of CASA is a Windows executable file, which will not run under Linux and Mac OS.

**Closed** 2016-11-16 14:18 UTC
Labels: bug (major), General
