### ISSUE TITLE
Collapsing siblings without children adds unnecessary legend item

### ISSUE THREAD

**Issue by TimoGuenther** [FeatureIDE/FeatureIDE#439] opened 2016-10-19 17:28 UTC
Steps to reproduce:

1. Create a feature model containing a feature with siblings. At least one of those siblings must not have any children.
2. Collapse the siblings of the feature using the "collapse siblings" context menu entry.

Example:
![collapsesiblingslegend2](https://cloud.githubusercontent.com/assets/18397625/19529488/5cc19ffc-9630-11e6-8c17-d9842c745205.png)

Note that nothing is collapsed but the legend item for collapsed features still shows up.

This symptom can be fixed by adding children to the formerly child-less siblings. It cannot be fixed by expanding the sibling; after all, it has no children, meaning its collapsed state may not be toggled. Neither can it be fixed by using the "expand all" context menu entry.

**Comment by TimoGuenther** [comment] 2016-10-19 17:39
I have not looked at the code, but my guess is that the "collapse siblings" routine fails to check whether each sibling can actually be collapsed. Instead, it just sets each sibling to a collapsed state (which cannot be undone easily because every other routine to collapse actually does the check). As a result, the sibling assumes the collapsed state, which has no visible effect outside of the legend because it has no children. Then, once the legend is being updated, a collapsed item is found (though it is not visible to the user) and the unnecessary legend item is added.

**Comment by tthuem** [comment] 2016-10-19 17:44
Related to #435

**Comment by Subaro** [comment] 2016-10-20 12:44
The issue is now fixed on bs_team1 branch

**Closed by Subaro** 2016-10-20 12:44 UTC
Labels: bug (minor), Feature Modeling

**Comment by tthuem** [comment] 2016-10-21 13:21
Thanks Joshua :)
