### ISSUE TITLE
Make GUI tests great again

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#791] opened 2018-06-29 05:43 UTC
GUI tests are running on Travis and Jenkins. We have only 5 activated tests so far as all others fail. 

https://github.com/FeatureIDE/FeatureIDE/blob/d50113ba9c0673425256f2137de2b392ceb2d1d9/gui-tests/de.ovgu.featureide.fm.gui-test/pom.xml#L40-L59

It needs to be investigated why those other GUI tests fail and whether this indicates actual bugs or is just our GUI tests need updates. Please create a separate branch for that based on release3.5 and create issues if actual bugs have been identified.

**Comment by tthuem** [comment] 2018-06-30 21:59
Sporadically the following tests fail on Travis:

```
[INFO] Pass 1 (5) processed. 0 failed. spent: 0:33, 0:33 mins remaining. CreateFeatureModelInFeatureIDEProject. time: 33104ms 
[INFO] Pass 2 (5) processed. 0 failed. spent: 1:14, 1:14 mins remaining. CreateFeatureModelInJavaProject. time: 40181ms 
[INFO] Pass 3 (5) processed. 0 failed. spent: 1:24, 0:16 mins remaining. EditConfiguration. time: 9229ms 
[INFO] Fail 4 (5) processed. 1 failed. spent: 4:26, 0:53 mins remaining. ExplainingAnomaliesInFeatureDiagram. time: 182522ms  Cause: Execution timed out after 180 seconds
[INFO] 
[INFO] 
[INFO] Possible AUT hang detected, 2 tests are failed because of timeout. Restarting AUT.
[INFO] 
[INFO] 
[INFO] Fail 5 (5) processed. 2 failed. spent: 7:27, 0:00 mins remaining. SelectingFeaturesInFeatureDiagram. time: 180160ms  Cause: Execution timed out after 180 seconds
```

Seems that Eclipse freezes for some reason.

**Comment by tthuem** [comment] 2018-08-23 13:15
Pre-packaged eclipse for GUI tests and wiki entry how to create it.

**Comment by Subaro** [comment] 2018-08-29 15:39
Currently, the release does not run successfully. The following is shown in the log:

```
Fail 1 (5) processed. 1 failed. spent: 0:58, 0:58 mins remaining. CreateFeatureModelInFeatureIDEProject. time: 57156ms  Cause: The Window "Editors available on marketplace" could not be found.
[INFO] Fail 2 (5) processed. 2 failed. spent: 1:46, 0:53 mins remaining. CreateFeatureModelInJavaProject. time: 47356ms  Cause: The Window "Editors available on marketplace" could not be found.
```

It seems the gui test cannot find the specific window `Editors available on marketplace`

**Comment by tthuem** [comment] 2018-09-05 15:27
@Subaro Some time ago I had to add this window into a couple of tests to make them work. It seems that it is not popping up anymore. Please remove it from the tests.

**Comment by PaulWestphal** [comment] 2019-03-30 18:52
As of right now, these GUI tests are working on the branch issue_791:

CreateFeatureModelInFeatureIDEProject
CreateFeatureModelInJavaProject
CreateFeaturesInFeatureDiagram
EditConfiguration
ExplainingAnomaliesInFeatureDiagram
SelectingFeaturesInFeatureDiagram
SetAbstractInFeatureDiagram
SetCollapsedInFeatureDiagram
SetHiddenInFeatureDiagram

**Comment by tthuem** [comment] 2019-04-01 09:29
@Subaro Are we planning to use a new tool for GUI tests or do we continue with the current infrastructure?

**Comment by Subaro** [comment] 2019-04-15 08:48
I found RedDeer and SWTBot that could be used to automate GUI tests for eclipse. How we proceed further should be discussed in the meeting.

**Comment by Subaro** [comment] 2019-04-23 12:27
### **Possible replacements for RCPTT (GUI Test Tool):** [Issue 791](https://github.com/FeatureIDE/FeatureIDE/issues/791)

[**1. RedDeer:**](https://projects.eclipse.org/projects/technology.reddeer)
* "The Eclipse RedDeer project is an extensible framework used for development of automated SWT/Eclipse tests which interacts with application’s user interface"
* Tests are programmed and not recorded:
```
@Test
	public void redDeerTestExample() {
		
		// Create Java Project
		JavaProjectWizard projectDlg = new JavaProjectWizard();
		projectDlg.open();
		NewJavaProjectWizardPageOne projectPage = new NewJavaProjectWizardPageOne(projectDlg);
		projectPage.setProjectName("testProject");
		projectDlg.finish();
		
		// Create Java class
		NewClassCreationWizard classDlg = new NewClassCreationWizard();
		classDlg.open();
		NewClassWizardPage classPage = new NewClassWizardPage(classDlg);
		classPage.setName("RedDeerDemo");
		classPage.setPackage("org.reddeer.demo");
		classDlg.finish();
		
		// Edit Java class
		TextEditor textEditor = new TextEditor("RedDeerDemo.java");
		textEditor.setText("Written by RedDeer");
		textEditor.save();
		
		// Check ProblemsView
		ProblemsView problemsView = new ProblemsView();
		problemsView.open();
		assertFalse(problemsView.getProblems(ProblemType.ERROR).isEmpty());
	}
```

[**2. SWTBot:**](https://projects.eclipse.org/projects/technology.swtbot)
* "SWTBot is an open-source Java based UI/functional testing tool for testing SWT, Eclipse and GEF based applications."
* Also programmed and not recorded:
```
@Test
    public void test() {
        // find the text after the label "My Label"
        SWTBotText textWithLabel = bot.textWithLabel("My Label");
        // Set the focus and write a text into the text field
        textWithLabel.setFocus();
        assertEquals(textWithLabel.getText(), "This is my text");
        textWithLabel.selectAll();
        textWithLabel.typeText("Java rules them all");
        assertEquals(textWithLabel.getText(), "Java rules them all");

        // find the text with with the assigned id
        SWTBotText textWithId = bot.textWithId("text1");
        assertEquals(textWithId.getText(), "This text has an ID");

        // now lets find a view part
        SWTBotView viewById = bot.viewById("de.vogella.swtbot.app.view");
        assertNotNull(viewById);

        // Select the exit menu
        // bot.menu("/File").menu("Exit").click();

        assertTrue(true);
    }
```

**Comment by PaulWestphal** [comment] 2019-06-04 11:54
As of right now, these GUI tests are working on the branch issue_791:

CreateFeatureModelInFeatureIDEProject.test
CreateFeatureModelInJavaProject.test
CreateFeaturesInFeatureDiagram.test
EditAdvancedConfiguration.test
EditConfiguration.test
ExplainingAnomaliesInFeatureDiagram.test
HandsOn1.test
HandsOn2.test
HandsOn3.test
SelectingFeaturesInFeatureDiagram.test
SetAbstractInFeatureDiagram.test
SetCollapsedInFeatureDiagram.test
SetHiddenInFeatureDiagram.test

And all fixes have been merged into develop. HandsOn4 is working for me locally, but not on travis for some reason. The HandsOn5 test is working as intended, but it fails due to an unhandled event loop exception (I will create a new issue for this).

**Comment by PaulWestphal** [comment] 2019-06-24 13:54
HandsOn5 should work again if this bug is fixed:

#890

**Comment by PaulWestphal** [comment] 2019-07-09 11:45
HandsOn4 is the only GUI test that is still not working.

https://github.com/FeatureIDE/FeatureIDE/issues/891

**Closed by PaulWestphal** 2019-07-09 11:45 UTC
Labels: General, enhancement
