### ISSUE TITLE
Revise and Merge new Imports, Improved Performance, and Statistics (Team 2)

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#436] opened 2016-10-19 08:10 UTC
Let us use this issue to discuss what changes are necessary prior to merge and to wrap up open issues afterwards.

![cam00004](https://cloud.githubusercontent.com/assets/5330357/19510524/f14191d4-95e3-11e6-97f2-c647ed70005b.jpg)
![cam00006](https://cloud.githubusercontent.com/assets/5330357/19510525/f2fb61da-95e3-11e6-82c4-28528de123a8.jpg)
![cam00007](https://cloud.githubusercontent.com/assets/5330357/19510529/f4d05e5c-95e3-11e6-9dce-aa015186e0d3.jpg)

**Comment by Kogoro** [comment] 2016-12-19 18:29
I performed some tests based on the tasks and find some things that should be removed for better user experience.
1. The context menu entry should be renamed as it is also the entry for antenna projects and only for legacy projects (see also 2.)
2. If you perform a project(FH or Antenna) in project(FH or Antenna) import through this context menu entry, there are some behaviors which should be solved or checked at least if its already a featureide project. To reproduce it, copy an example (e.g. "Hello-World") from workspace to another location. Create a new empty featureide project. Import the copied project into the empty project through the context menu entry.

Some Screenshots:
Antenna:
![screenshot from 2016-12-19 19 23 56](https://cloud.githubusercontent.com/assets/8019776/21324231/25360354-c621-11e6-8315-e0d352e16ba4.png)
FeatureHouse:
![screenshot from 2016-12-19 19 26 01](https://cloud.githubusercontent.com/assets/8019776/21324232/25379d5e-c621-11e6-92b6-34091e002b08.png)

**Comment by tthuem** [comment] 2017-01-17 13:59
The importer could be used to import all FeatureHouse examples into FeatureIDE and add them as examples in FeatureIDE.

**Comment by Kogoro** [comment] 2017-09-13 21:34
The branch is more or less unreviewable. So we decided to not take in any commit. 
Also the double click bug in the statistics view seems to be resolved (maybe through #463?).
@Subaro also takes a look whether the bug is resolved or not. When the bug is resolved the issue can be closed.

**Comment by Kogoro** [comment] 2017-09-14 10:33
Closing this as the double-click bug seems resolved in the meantime.

**Closed by Kogoro** 2017-09-14 10:33 UTC
Labels: Antenna, enhancement, FeatureHouse, General
