### ISSUE TITLE
Feature Color has no effect 

### ISSUE THREAD

**Issue by alkalinan** [FeatureIDE/FeatureIDE#728] opened 2018-03-22 12:02 UTC
#### Prerequisitives
* **Eclipse Version:**  `Oxygen.2 Release (4.7.2)`
* **FeatureIDE-Version:**  `3.4.3`
* **Operating system:** `MacOS 10.11.6`
* **Java runtime used to run eclipse:** `Java SE 8`
* **FeatureIDE Composer:** `Munge (Android) and Munge (I have not test the rest)`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When trying to set up FeatureColor for on the feature model or on the Collaboration Diagram, pressing the "Ok" button has no effect. Plus the "Set Feature Colors" windows do not disappear after pressing "Ok". 

![capture d ecran 2018-03-22 a 13 00 20](https://user-images.githubusercontent.com/19858911/37769377-19eaeb40-2dd1-11e8-859a-f88af5fe4e84.png)

**Comment by alkalinan** [comment] 2018-03-22 14:03
Solution : Color Schemes was not configured at first. This feature needs to return a message error of the color scheme is not set.

**Comment by tthuem** [comment] 2018-03-26 10:15
@PaulWestphal Is it related to #684?

**Comment by alkalinan** [comment] 2018-03-26 10:29
It seems like yes

**Comment by Kogoro** [comment] 2018-03-26 13:10
Seems to be a duplicate of #708 (fixed for the upcoming release 3.5)

**Closed** 2018-03-26 13:14 UTC
Labels: duplicate
