### ISSUE TITLE
New constraint wizard highlights logical keywords in feature names.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#625] opened 2017-10-09 12:53 UTC
Screenshot should be self-explanatory.

![screenshot from 2017-10-09 14-49-33](https://user-images.githubusercontent.com/32126695/31338964-9213e96a-ad01-11e7-9277-f7218cf368ee.jpg)

**Comment by Kogoro** [comment] 2017-10-09 14:09
Duplicate of #178

**Closed by Kogoro** 2017-10-09 14:09 UTC
Labels: duplicate
