### ISSUE TITLE
New constraint wizard should not highlight logical keywords in feature names

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#669] opened 2017-11-21 12:10 UTC
### Issue description
The coloring of operators in constraint dialog is also colored when occurring in feature names.

Light theme:
<img width="181" alt="unbenannt" src="https://user-images.githubusercontent.com/6231523/33071789-39679f40-cebd-11e7-9013-7c25f82477a0.PNG">

Dark theme:
<img width="190" alt="unbenannt2" src="https://user-images.githubusercontent.com/6231523/33071793-3ba5dd1c-cebd-11e7-97ed-e6150eb3d6e4.PNG">

**Comment by Kogoro** [comment] 2017-11-21 15:06
Duplicate of #178 and #625.

**Closed** 2017-11-21 15:06 UTC
Labels: duplicate
