### ISSUE TITLE
User-defined Feature Order has no effect when using FeatureHouse

### ISSUE THREAD

**Issue by AlexanderKnueppel** [FeatureIDE/FeatureIDE#1140] opened 2021-07-03 13:17 UTC
#### Prerequisitives
* **FeatureIDE-Version:**  `3.7.0`

### Issue description
For FOP, it is clearly necessary to be able to manually change the order of composition in the featue model. The user-defined order, however, has currently no affect when used with FeatureHouse. This can be replicated with the HelloWorld Example and multiple students reported the same problem with their projects.

I couldn't find related issues, so I think there is still no fix to this in the current version. Can anyone comment on this? Maybe there is a workaround besides re-ordering features in the model.xml file?

**Comment by ekuiter** [comment] 2021-12-09 14:31
Our students have reproduced this. (temporary fix: reorder features in the feature tree)

**Comment by ekuiter** [comment] 2022-04-08 13:59
The bug is in `FeatureHouseComposer.createTemporaryConfigrationFile`, where the configuration is serialized with `DefaultFormat` into a file that is fed into FeatureHouse. Here, the feature order should be respected, but it is not, because the Configuration read with the `FileHandler` is not associated with the project's feature model (so it does not know about the supposed feature order).

My suggestion is to call `configuration.updateFeatures(...)` to link the configuration to the feature model. I have a working fix. Can someone remind me on which branch I have to commit/merge this to be included in 3.8.2? I rarely do pull requests :')

**Comment by tthuem** [comment] 2022-04-11 10:38
Great, we need the fix here: https://github.com/FeatureIDE/FeatureIDE/tree/release3.7

**Comment by skrieter** [comment] 2022-04-29 07:51
Fixed in #1339

**Closed by skrieter** 2022-04-29 07:51 UTC
Labels: bug (major), FeatureHouse
