### ISSUE TITLE
Fuji not working with Java 8

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#87] opened 2014-07-02 16:09 UTC
Fuji calls System.exit() when using Java 8, such that the JVM and Eclipse close (e.g. just import GPL-FH-Java).
There is some issue inside of Fuji, so this bug should be reported to them.

Possible workaround until Fuji is fixed:
see:http://stackoverflow.com/questions/309396/java-how-to-test-methods-that-call-system-exit

use@ FeatureHouseComposer runFuji: 
System.setSecurityManager(new NoExitSecurityManager());

class NoExitSecurityManager extends SecurityManager 
    {
        @Override
        public void checkPermission(Permission perm) 
        {
            // allow anything.
        }
        @Override
        public void checkPermission(Permission perm, Object context) 
        {
            // allow anything.
        }
        @Override
        public void checkExit(int status) 
        {
            super.checkExit(status);
            throw new ExitException(status);
        }
    }

**Comment by tthuem** [comment] 2015-01-20 13:57
Is this problem still valid? A disapearing Eclipse is the worst error and should definetely be fixed for the next version...

**Comment by pinnecke** [comment] 2015-01-22 17:28
I'm unable to reproduce the *System.exit()* call. But running FeatureIDE with the following configurations for *FeatureHouse HelloWorld Example*:

**JRE**:	Java SE 8 [1.8.0_20]
**JDK Compiliance Level**: 1.8
**Eclipse Application launch configurations, JRE**:	JavaSE-1.7 [1.8.0_80]

will lead to an internal exception inside *fuji.jar*.

```
Exception in thread "Thread-Type checking HelloWorld-FH-Java with fuji" java.lang.Error: Error loading java.lang.CharSequence
	at AST.PathPart.getCompilationUnit(PathPart.java:131)
	at AST.Program.getCompilationUnit(Program.java:266)
	at AST.Program.lookupType_compute(Program.java:1459)
	at AST.Program.lookupType(Program.java:1440)
	at AST.Program.Define_TypeDecl_lookupType(Program.java:1998)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.Expr.lookupType(Expr.java:1363)
	at AST.TypeAccess.decls_compute(TypeAccess.java:490)
	at AST.TypeAccess.decls(TypeAccess.java:479)
	at AST.TypeAccess.decl_compute(TypeAccess.java:527)
	at AST.TypeAccess.decl(TypeAccess.java:517)
	at AST.TypeAccess.type_compute(TypeAccess.java:704)
	at AST.TypeAccess.type(TypeAccess.java:697)
	at AST.ParameterDeclaration.type_compute(ParameterDeclaration.java:444)
	at AST.ParameterDeclaration.type(ParameterDeclaration.java:437)
	at AST.MethodDecl.signature_compute(MethodDecl.java:1333)
	at AST.MethodDecl.signature(MethodDecl.java:1321)
	at AST.TypeDecl.localMethodsSignatureMap_compute(TypeDecl.java:2814)
	at AST.TypeDecl.localMethodsSignatureMap(TypeDecl.java:2802)
	at AST.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1189)
	at AST.ClassDecl.methodsSignatureMap(ClassDecl.java:1181)
	at AST.TypeDecl$2.<init>(TypeDecl.java:485)
	at AST.TypeDecl.methodsIterator(TypeDecl.java:484)
	at AST.TypeDecl.methodsNameMap_compute(TypeDecl.java:2751)
	at AST.TypeDecl.methodsNameMap(TypeDecl.java:2742)
	at AST.TypeDecl.memberMethods_compute(TypeDecl.java:2717)
	at AST.TypeDecl.memberMethods(TypeDecl.java:2710)
	at AST.AbstractDot.Define_Collection_lookupMethod(AbstractDot.java:902)
	at AST.Expr.lookupMethod(Expr.java:1209)
	at AST.MethodAccess.refined_LookupMethod_MethodAccess_decls(MethodAccess.java:1055)
	at AST.MethodAccess.decls_compute(MethodAccess.java:1263)
	at AST.MethodAccess.decls(MethodAccess.java:1255)
	at AST.MethodAccess.splTypeCheck(MethodAccess.java:571)
	at AST.ASTNode.collectSplErrors(ASTNode.java:689)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.Program.splErrorCheck(Program.java:719)
	at fuji.Main.typecheckAST(Main.java:443)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.runFuji(FeatureHouseComposer.java:712)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.access$2(FeatureHouseComposer.java:698)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer$3.work(FeatureHouseComposer.java:678)
	at de.ovgu.featureide.fm.core.job.AStoppableJob$InnerThread.run(AStoppableJob.java:55)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20492
	at AST.BytecodeParser.parseThisClass(BytecodeParser.java:440)
	at AST.BytecodeParser.parseTypeDecl(BytecodeParser.java:416)
	at AST.BytecodeParser.parse(BytecodeParser.java:334)
	at AST.BytecodeParser.read(BytecodeParser.java:30)
	at AST.PathPart.getCompilationUnit(PathPart.java:118)
	... 57 more
```

**Comment by pinnecke** [comment] 2015-01-22 18:03
## Conclusion
Fuji throws the exception described above when using it with JRE 8 inside the target eclipse.

## Fuji Version information
Last official version of fuji is  [Fuji. Version 2012-03-26](http://www.infosun.fim.uni-passau.de/spl/apel/fuji/#download) which means, as far as I can see, FeatureIDE uses the latest available version.

## Runtime and Environment Stability Overview
In the following I present JRE/JDK and JRE (Target) combinations and if Fuji works or if does not.

#### Configurations in which fuji works
**FeatureIDE JDK Compiliance Level**:	1.7
**Eclipse Application launch configurations, JRE**:	Java SE 7 [1.7.0_80]

#### Configurations in which it throws an exception
**FeatureIDE JDK Compiliance Level**:	1.7
**Eclipse Application launch configurations, JRE**:	 _Java SE 8 [1.8.0_20]_

**FeatureIDE JDK Compiliance Level**:	1.7
**Eclipse Application launch configurations, JRE**:	_Java SE 8 [1.8.0_20]_

**FeatureIDE JDK Compiliance Level**:	1.8
**Eclipse Application launch configurations, JRE**:	_Java SE 8 [1.8.0_20]_

**Comment by pinnecke** [comment] 2015-01-22 19:41
Thomas please have a look if the sources of *Futji* fork, which is used in Feature IDE, is still available.

**Comment by tthuem** [comment] 2015-01-23 08:19
Jens, please clarify whether we have a customized version of Fuji.

**Comment by tthuem** [comment] 2015-01-26 11:47
I contacted the Fuji developers for a current version of the source code.

**Comment by pinnecke** [comment] 2015-01-28 10:32
Grant access to source repository from Fuji devlopers. Unfortunally the ANT script doesn't work because of access permisssion. In order to get these, I contacted the developers by myself.

**Comment by pinnecke** [comment] 2015-01-29 21:23
Fuji references against ```sun.org.mozilla.javascript.ast```package which is **(a)** an illegal import of the internal JRE and **(b)** unused.

**Comment by pinnecke** [comment] 2015-03-10 13:54
I can reproduce the exception in some tests in Fuji directly. According to Sergiy Kolesnikov the exception is thrown by *JustAddJ*, a library he uses. As far as I can see, the exception occurs at least when `java.lang.CharSequence` (which is an interface) is parsed by *JustAddJ* in *Fuji* when *FeatureIDE* calls the Fuji-Typecheck. However, Java 8 introduces *default* method implementations for interfaces which seems to be the reason for that problem. The exception is caused by 

`
 java.lang.ArrayIndexOutOfBoundsException: 20492
	at AST.BytecodeParser.parseThisClass(BytecodeParser.java:440)
	at AST.BytecodeParser.parseTypeDecl(BytecodeParser.java:416)
	at AST.BytecodeParser.parse(BytecodeParser.java:334)
	at AST.BytecodeParser.read(BytecodeParser.java:30)
	at AST.PathPart.getCompilationUnit(PathPart.java:118)
`

This index out of bounds comes from the access to a field which models the JDK's *constant pool* inside the *JustAddJ* byte parser class.

**Comment by pinnecke** [comment] 2015-03-10 14:22
*JustAddJ* parses a class file and build the constant pool for it. By doing so, it adds a entry to the constant pool for each entry in the class file.

*JustAddJ* supports

* Class: identified by unsigned byte 7
* FieldRef: identified by unsigned byte 9
* MethodRef: identified by unsigned byte 10
* InterfaceMethodRef: identified by unsigned byte 11
* String: identified by unsigned byte 8
* Integer: identified by unsigned byte 3
* Float: identified by unsigned byte 4
* Long: identified by unsigned byte 5 
* Double: identified by unsigned byte 6
* NameAndType: identified by unsigned byte 12
* Utf8: identified by unsigned byte 1

but **18** is required.

**Comment by pinnecke** [comment] 2015-03-10 14:27
According to oracle's [jvm spec](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html) for 1.8, the constant pool tag **18** is defined for 

* **CONSTANT_InvokeDynamic**. 

By the way *JustAddJ* does obviously also not support 

* **CONSTANT_MethodHandle**	(**15**)
* **CONSTANT_MethodType** (**16**)

**Comment by pinnecke** [comment] 2015-03-10 15:25
The *JastAddJ* published a updates version for *Java 1.8* for which I assume it can handle the new spec. However, I ask the developer of *Fuji* zu update to this version. Probability this should solve the bug.

**Comment by pinnecke** [comment] 2015-03-10 17:19
**QuickFix** for Fuji Typechecker exception when running on JRE 8. Fix: Fuji cannot enabled if JRE 8 is used. When the user wants to enable it, a message box opens to inform him about that. Merged into Master and will be replaces, when Fuji supports Java 1.8.

**Comment by pinnecke** [comment] 2015-03-11 11:14
The developer of Fuji will update Fuji to JastAddJ as soon as he is able to do that. Meanwhile the quick fix above is active.

**Comment by tthuem** [comment] 2015-05-11 08:18
Any news on that?

**Comment by pinnecke** [comment] 2015-05-11 19:05
Last update in Fuji repository was reported on 2015-02-01. Hence, there are no new here.

**Comment by jabiercoding** [comment] 2016-04-19 12:37
FeatureIDE closed completely! The workaround was to change from Java 8 to Java 7. The error message is different so I report it here as it may be related. Let me know if you think that I should open it in a separated one.

This is a minimal example that I found to reproduce the issue I am having with my project: select FeatureHouse composer, use this snippet as implementation of a feature and select it in a configuration.

```
import java.util.Hashtable;
public class Main {
	public Hashtable<String, String> info = new Hashtable<String, String>();
}
```

During the build FeatureIDE will close in Java 8, but it will work in Java 7. This is the trace:

```
java.lang.ClassCastException: AST.CONSTANT_NameAndType_Info cannot be cast to AST.CONSTANT_Class_Info
	at AST.BytecodeParser.parseThisClass(BytecodeParser.java:440)
	at AST.BytecodeParser.parseTypeDecl(BytecodeParser.java:407)
	at AST.BytecodeParser.parse(BytecodeParser.java:334)
	at AST.BytecodeParser.parse(BytecodeParser.java:304)
	at AST.Attributes$TypeAttributes.innerClasses(Attributes.java:415)
	at AST.Attributes$TypeAttributes.processAttribute(Attributes.java:319)
	at AST.Attributes.attributes(Attributes.java:64)
	at AST.Attributes$TypeAttributes.<init>(Attributes.java:310)
	at AST.BytecodeParser.parse(BytecodeParser.java:340)
	at AST.BytecodeParser.read(BytecodeParser.java:30)
	at AST.PathPart.getCompilationUnit(PathPart.java:118)
	at AST.Program.getCompilationUnit(Program.java:266)
	at AST.Program.lookupType_compute(Program.java:1459)
	at AST.Program.lookupType(Program.java:1440)
	at AST.Program.Define_TypeDecl_lookupType(Program.java:1998)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.Expr.lookupType(Expr.java:1363)
	at AST.TypeAccess.decls_compute(TypeAccess.java:490)
	at AST.TypeAccess.decls(TypeAccess.java:479)
	at AST.TypeAccess.decl_compute(TypeAccess.java:527)
	at AST.TypeAccess.decl(TypeAccess.java:517)
	at AST.TypeAccess.type_compute(TypeAccess.java:704)
	at AST.TypeAccess.type(TypeAccess.java:697)
	at AST.ParTypeAccess.genericDecl_compute(ParTypeAccess.java:362)
	at AST.ParTypeAccess.genericDecl(ParTypeAccess.java:356)
	at AST.ParTypeAccess.type_compute(ParTypeAccess.java:336)
	at AST.ParTypeAccess.type(ParTypeAccess.java:328)
	at AST.ParameterDeclaration.type_compute(ParameterDeclaration.java:444)
	at AST.ParameterDeclaration.type(ParameterDeclaration.java:437)
	at AST.List.substitute(List.java:104)
	at AST.ConstructorDecl.p(ConstructorDecl.java:538)
	at AST.ParClassDecl.constructors_compute(ParClassDecl.java:2004)
	at AST.ParClassDecl.constructors(ParClassDecl.java:1993)
	at AST.ClassInstanceExpr.decls_compute(ClassInstanceExpr.java:991)
	at AST.ClassInstanceExpr.decls(ClassInstanceExpr.java:982)
	at AST.ClassInstanceExpr.splTypeCheck(ClassInstanceExpr.java:513)
	at AST.ASTNode.collectSplErrors(ASTNode.java:689)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.Program.splErrorCheck(Program.java:719)
	at fuji.Main.typecheckAST(Main.java:443)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.runFuji(FeatureHouseComposer.java:511)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.access$1(FeatureHouseComposer.java:493)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer$3.execute(FeatureHouseComposer.java:478)
	at de.ovgu.featureide.fm.core.StoppableJob$1.run(StoppableJob.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tthuem** [comment] 2016-06-21 20:30
Seems that we need to live with the fact that Fuji does not support Java 1.8. If there is an update of Fuji, we would be happy to integrate it.

**Closed by tthuem** 2016-06-21 20:30 UTC
Labels: bug (critical), FeatureHouse, Pending
