### ISSUE TITLE
Redundant constraints cannot be edited

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#622] opened 2017-10-08 14:05 UTC

**Comment by Kogoro** [comment] 2017-10-12 08:26
Seems to be caused by #619 as the selection will not be updated through the exception call which leads to an old selection state.

**Comment by TimoGuenther** [comment] 2017-10-12 11:17
On `develop`, when I edit a constraint, an error message with the exception from https://github.com/FeatureIDE/FeatureIDE/issues/619 pops up, but the constraint still changes. Is that the symptom?

On `explanations`, I cannot reproduce any such issue.

**Comment by tthuem** [comment] 2017-10-12 11:49
I've seen the problem that a redundant constraint cannot be opened in constraint dialog and cannot be removed. There was no error popup, but there could habe been one in the error log.

@Kogoro Can you confirm this behavior on your setting for develop?

@TimoGuenther If you have completely different behavior this could be due to different operating system, but still feels unlikely for that behavior.

**Comment by TimoGuenther** [comment] 2017-10-12 11:58
I tested this using Eclipse Oxygen on Linux Mint and Windows 7.

**Comment by Subaro** [comment] 2017-10-13 16:04
On current develop as of `22abb50a65f4efa6f2517a84fd080f9933e2d2df` i can edit redundant constraints without any problem.

**Comment by tthuem** [comment] 2017-10-16 10:07
Prior to merging the branches of the team project, we should check whether it works there two. It could be an issue introduced by their changes. Who can test in in all three team branches (once they are complete)?

**Comment by Subaro** [comment] 2018-01-04 09:56
Currently it works on:

* [x] release
* [ ] develop
* [ ] Team 1
* [ ] Team 2
* [ ] Team 3 (can be ignored because it won't be merged)

**Closed** 2018-01-04 09:58 UTC
Labels: bug (major), Feature Modeling
