### ISSUE TITLE
Key-value properties not stored persistently for feature models

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#373] opened 2016-07-20 06:27 UTC
Marcus, you wanted to provide us some pointers on how to fix that.

**Comment by pinnecke** [comment] 2016-07-20 13:03
Canot reproduce the issue. Custom properties are stored and loaded correctly. I created a test (`de.ovgu.featureide.fm.core.base.CustomPropertiesTest.java`) in branch `issue_373`:


			//... create model, add properties and store the model in  "modelFile"

			final IFeatureModel model = factory.createFeatureModel();		 		
			final XmlFeatureModelReader reader = new XmlFeatureModelReader(model);
			reader.readFromFile(modelFile);
			
			Assert.assertTrue(model.getFeature("A").getCustomProperties().has("key1"));
			Assert.assertTrue(model.getFeature("B").getCustomProperties().has("key1"));
			Assert.assertTrue(model.getFeature("C").getCustomProperties().has("key2"));
			Assert.assertTrue(model.getFeature("C").getCustomProperties().has("key3"));
			
			Assert.assertFalse(model.getFeature("A").getCustomProperties().has("key2"));
			Assert.assertFalse(model.getFeature("B").getCustomProperties().has("key3"));
			Assert.assertFalse(model.getFeature("C").getCustomProperties().has("key1"));
			
			Assert.assertTrue(model.getFeature("A").getCustomProperties().getDataType("key1").equals(Type.STRING));
			Assert.assertTrue(model.getFeature("B").getCustomProperties().getDataType("key1").equals(Type.STRING));
			Assert.assertTrue(model.getFeature("C").getCustomProperties().getDataType("key2").equals(Type.INT));
			Assert.assertTrue(model.getFeature("C").getCustomProperties().getDataType("key3").equals(Type.INT));
			
			Assert.assertTrue(((String) model.getFeature("A").getCustomProperties().get("key1")).equals("value1"));
			Assert.assertTrue(((String) model.getFeature("B").getCustomProperties().get("key1")).equals("value1"));
			Assert.assertTrue(((Integer) model.getFeature("C").getCustomProperties().get("key2")).equals(23));
			Assert.assertTrue(((Integer) model.getFeature("C").getCustomProperties().get("key3")).equals(23));
			
			model.getFeature("A").getCustomProperties().remove("key1");
			Assert.assertFalse(model.getFeature("A").getCustomProperties().has("key1"));
			
			modelFile.delete();			
			final XmlFeatureModelWriter writer = new XmlFeatureModelWriter(model);	
			writer.writeToFile(modelFile);
			final IFeatureModel model2 = factory.createFeatureModel();		 		
			new XmlFeatureModelReader(model2).readFromFile(modelFile);
			
			Assert.assertFalse(model2.getFeature("A").getCustomProperties().has("key1"));

**Comment by pinnecke** [comment] 2016-07-20 13:19
Also works with novel `Filehandler`, i.e., `FileHandler.save(modelFile.toPath(), model, new XmlFeatureModelFormat());` and `FileHandler.load(modelFile.toPath(), model, new XmlFeatureModelFormat());` for default implementations.

**Comment by pinnecke** [comment] 2016-07-20 13:39
Custom properties (i.e., key-value pairs over `Feature::getCustomProperties()`) works for me. The issue targets probably another topic. I found reading feature models from file throws custom implementations away (see wrongly use of default factory in `de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat:527`). Hence, the issue "Key-value properties not stored persistently for feature models" is likely "Reading feature models from file does not consider custom feature implementations".

**Comment by pinnecke** [comment] 2016-07-20 14:34
Sebastian, please take a look at `de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat:527`

**Comment by skrieter** [comment] 2016-08-24 11:03
Fixed in Branch [Core_Library](https://github.com/FeatureIDE/FeatureIDE/tree/Core_Library).
We plan to merge the branch at the end of September into develop.
Version 3.2.0 will include the bug fix.

(See also #374)

**Closed** 2016-10-12 09:00 UTC
Labels: bug (major), Feature Modeling
