### ISSUE TITLE
Tests in fm.core-test fail since merge of explanation branch

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#569] opened 2017-08-16 10:20 UTC
#### Prerequisitives
* **FeatureIDE-Version:**  `develop`
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `1.7`

### Issue description
Currently, 8 failures are happening when executing the fm.core-test. Some SatSolver Tests is not working.

I think it happens because of your merge @TimoGuenther

**Comment by TimoGuenther** [comment] 2017-08-16 10:30
I get 2 failures (testGeneralization2 and testDeleteAbstractFeatureRefactoring). Those were already mentioned in an e-mail from @tthuem on 2017-08-10 (you were in CC). Please read the mail I sent in response to it.

As for the other 6, I can't reproduce them. Which ones are failing?

**Comment by Subaro** [comment] 2017-08-30 11:34
@TimoGuenther 
I can have a look at the problems from the email. 

Also here are the other failures I get when running the core-tests.

### Overview
<img width="356" alt="unbenannt" src="https://user-images.githubusercontent.com/6231523/29870184-8fd0a4d0-8d86-11e7-9bc4-0cf22cceb800.PNG">

The first and second one was mentioned in the email. Here is the stack trace of the following 6:

### org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolverTests

1. testSatisfiableAssumtions:
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.SatSolverTests.testSatisfiableAssumptions(SatSolverTests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
2. testModelAssumptions
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.getModel(Sat4jSatSolver.java:115)
	at org.prop4j.explain.solvers.SatSolverTests.testModelAssumptions(SatSolverTests.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

### org.prop4j.explain.solvers.impl.sat4j.Sat4jMutableSatSolverTests
1. testSatisfiableAssumptions
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.SatSolverTests.testSatisfiableAssumptions(SatSolverTests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
2. testModelAssumptions
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.getModel(Sat4jSatSolver.java:115)
	at org.prop4j.explain.solvers.SatSolverTests.testModelAssumptions(SatSolverTests.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```


### org.prop4j.explain.solvers.impl.sat4j.Sat4jMusExtractorTests
1. testSatisfiableAssumptions
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.sat4j.tools.AbstractClauseSelectorSolver$1.isSatisfiable(AbstractClauseSelectorSolver.java:88)
	at org.sat4j.tools.AbstractClauseSelectorSolver.isSatisfiable(AbstractClauseSelectorSolver.java:164)
	at org.sat4j.tools.xplain.Xplain.isSatisfiable(Xplain.java:192)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.SatSolverTests.testSatisfiableAssumptions(SatSolverTests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
2. testModelAssumptions
```
java.lang.AssertionError
	at org.sat4j.minisat.constraints.cnf.Lits.getFromPool(Lits.java:119)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1938)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1555)
	at org.sat4j.tools.AbstractClauseSelectorSolver$1.isSatisfiable(AbstractClauseSelectorSolver.java:88)
	at org.sat4j.tools.AbstractClauseSelectorSolver.isSatisfiable(AbstractClauseSelectorSolver.java:164)
	at org.sat4j.tools.xplain.Xplain.isSatisfiable(Xplain.java:192)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.isSatisfiable(Sat4jSatSolver.java:107)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jSatSolver.getModel(Sat4jSatSolver.java:115)
	at org.prop4j.explain.solvers.SatSolverTests.testModelAssumptions(SatSolverTests.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by TimoGuenther** [comment] 2017-08-30 16:36
I can reproduce all 8 failures now that I have reinstalled Eclipse (of any version, even the same version as before). Not sure which settings could have messed that up, but I'll be using the new installation from now on anyway.

More importantly, the 6 failures related to the SAT solver are fixed as of https://github.com/FeatureIDE/FeatureIDE/commit/3d6f367d1fe5b59120e9b54b8e77079f64c1a2ac.

**Comment by tthuem** [comment] 2017-09-06 10:55
@TimoGuenther The two remaining tests fail since https://github.com/FeatureIDE/FeatureIDE/commit/48613afee4e0eb0c3069e0843cb9080dbcad2a48. Please have a look.

**Comment by TimoGuenther** [comment] 2017-09-06 15:59
The remaining 2 failures are fixed as of https://github.com/FeatureIDE/FeatureIDE/commit/3d013ddd4471259f450adde472bc7356c6c3c58a.

**Closed by TimoGuenther** 2017-09-06 15:59 UTC
Labels: bug (major), Feature Modeling

**Comment by tthuem** [comment] 2017-09-06 16:25
Indeed, nightly builds work fine again. Thanks!
