### ISSUE TITLE
Deactivation of automated analyses is not stored persistently

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#573] opened 2017-09-01 10:27 UTC

**Comment by tthuem** [comment] 2017-09-01 10:53
Impossible to work with any larger models, as automated analyses are turned on automatically.

**Comment by tthuem** [comment] 2017-09-01 11:11
It seems that the menu is simply ignoring what is written in the file. Any change then leads to analyses being turned on.

**Comment by Subaro** [comment] 2017-09-03 13:45
The problem is that the changes made in the source tab are completely ignored. I investigated the problem a little bit further and saw that the model that is read from the model file is not the same as the currently used by the feature model editor. But there are so many Formats, Reader, Writer that I lost the overview.

The currently used format should be XmlFeatureModelFormat, right? The read method is used one time and the resulting feature model has an analyser with auto calculation deactivated. But unfortunately, the feature model that is provided for the feature diagram editor has another analyser with auto calculation activated. 

I think somewhere is missing a loading of the feature model.

**Comment by Subaro** [comment] 2017-09-03 13:49
Also changing the auto calculation in the feature diagram editor changes the feature model. But when saving, not the analyser from the feature diagram editor feature model is used, because it will always save the value "true" for automated analyse.

**Comment by Kogoro** [comment] 2017-09-03 15:24
Should be fixed with e300fd85a99da35e10be2a3b7602201f14050cb6
The analyzer was not copied when a copy of the feature model was created.

**Closed by Kogoro** 2017-09-03 15:24 UTC
Labels: bug (critical), Feature Modeling
