### ISSUE TITLE
Feature model Export As throws error Unknown image file format

### ISSUE THREAD

**Issue by nuttyengineer** [FeatureIDE/FeatureIDE#1371] opened 2022-09-02 09:13 UTC
#### Prerequisitives
* **Eclipse Version:**  `2021-06 (4.20)`
* **FeatureIDE-Version:**  `3.8.3 (also 3.7.1)`
* **Operating system:** `Windows 64bit`
* **Java runtime used to run eclipse:** `openjdk build 18.0.2+9-61`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When exporting a Feature model (right click in Model editor > **Export As** in menu > entered **File name** without entering the file type extension > selected **Save as type** > **Save**) to an image file (png, bmp, svg etc) an error message is received which states 'Save image' has encountered a problem. An internal error has occurred. Unknown image file format.:
![image](https://user-images.githubusercontent.com/112690648/188106515-e1c5a926-ac83-406f-a3cb-519a931fa180.png)

After trying different file types and earlier versions on FeatureIDE I realised that I needed to enter the file extension type at the end of the filename in the **File name** field to avoid the error. This does mean that the selected **Save as type** can be different to the manually entered file extension type in the filename field. The **Save as type** doesn't seem to have any effect on the saved file type.
![image](https://user-images.githubusercontent.com/112690648/188102952-aad6da3c-18c9-4d50-9e77-eeaf6b8871c0.png)

### Expected behaviour
This could be improved to make the **Export As** / **Save As** behave as in other programs i.e. the user types only the name of the file (excluding the file extension type) in the **File name** field, the file type is selected from the **Save as type**, the file is saved with the [filename]+[fileextensiontype]

**Comment by tthuem** [comment] 2022-09-05 04:32
I can reproduce this issue.

@st-vi Can you have a look at this?

**Comment by st-vi** [comment] 2022-09-05 11:20
The FileDialog from swt currently has no way to access the selected file extension (https://bugs.eclipse.org/bugs/show_bug.cgi?id=546256), which is due to a bug in GTK (https://gitlab.gnome.org/GNOME/gtk/-/issues/1820). The GTK bug is fixed in version 3.24.21 (https://ftp.fau.de/gnome/sources/gtk+/3.24/gtk+-3.24.21.news), but I am not quite sure, how to change the GTK version used from FeatureIDE.

**Comment by skrieter** [comment] 2022-09-13 13:36
It works for

**Closed** 2022-09-14 13:41 UTC
Labels: bug (minor), Feature Modeling
