### ISSUE TITLE
Context-menu entry "Show Collapsed Constraints" disappears when unchecked.

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#577] opened 2017-09-08 17:02 UTC
#### Prerequisitives
* **Eclipse Version:**  Neon.2
* **FeatureIDE-Version:**  3.3.2
* **Operating system:** Win7
* **Java runtime used to run eclipse:** 1.8.0_144
* **FeatureIDE Composer:** 
* **Git branch/Commit-ID:**  develop
* **Java compiler used to build the FeatureIDE plugin:**

### Issue description
When initially opening the feature model diagram editor, the "Show Collapsed Constraints" menu entry is usally enabled.
When disabling this option, the menu entry disapears.
Even when there are no collapsed constraints, this behavior is confusing.

**Comment by Subaro** [comment] 2017-09-13 10:03
The Problem is that the menu entry "Show Collapsed Constraints" should not be visible. It is only shown when any constraints are or can be collapsed. That is not the case but the "showCollapsedConstraint" option from the model.xml is saved with the value true. Maybe the examples should be checked that the every "showCollapsedConstraint" is set to false. 

Or we can always show the menu entry to prevent the user from being confused.

**Comment by Kogoro** [comment] 2017-09-13 10:54
The reason for not showing it when not needed was to minimize the context menu length as the context menu grows.
But I get the error so maybe not hiding it will be the best fix for this case.
I think we should shortly discuss this in the meeting.

**Closed** 2017-09-13 13:46 UTC
Labels: bug (minor), Feature Modeling
