### ISSUE TITLE
Feature Model Outline defects

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#260] opened 2015-06-03 11:12 UTC
1. Make mandatory/optional circles smaller
2. FeatureIDE icon -> FeatureModel icon
3. constraint icons are uncler!
4. Outline always collapes when chenging the focus (e.g. click on outline ,click on editor)
5. Do not display invalid filters (hide fields...)
6. Outline not displayed for non FeatureIDE projects

**Comment by tthuem** [comment] 2015-06-03 11:28
So, we should wait with the version for this issue to be fixed?

**Comment by meinicke** [comment] 2015-06-03 11:38
Yes. At least that the outline always collapses makes it unusable.

**Comment by tthuem** [comment] 2015-06-03 13:25
OK, I adapt the milestone accordingly.

**Comment by pinnecke** [comment] 2015-06-03 14:05
Will fix it today.
Am 03.06.2015 15:25 schrieb "Thomas Thüm" <notifications@github.com>:

**Comment by pinnecke** [comment] 2015-07-01 18:12
1. Done
2. Done
3. Done
4. In Progress
5. Unclear. What do you mean?
6. The outline is part of feature project. What do you mean?

Please be a bit more explicit in (5) and (6)

**Comment by pinnecke** [comment] 2015-07-01 18:14
Cannot reproduce (4). Still happening in current master?

**Comment by meinicke** [comment] 2015-07-01 20:30
4 ask Sebastian (also use the FeatureIDE outline view and not the standard outline view)
5 the filter on the top are implementation specific (also use the FeatureIDE outline)
6 that doe not mater, when I open a model then I wnat to see the corresponding tree in the outline

**Comment by pinnecke** [comment] 2015-07-16 13:26
**4**) Auto collapse and auto expand do work now like expected. Since the auto node selection in outline based on reloading the entire model into the tree when focussing a feature figure in feature diagram, node selection in outline is currently no longer available.

**Comment by pinnecke** [comment] 2015-07-21 10:15
"Auto-Collapse"/"Auto-Expand" bug is fixed. Unfortunately, the auto-select feature (when clicking on a feature in feature diagram, then the related node in the outline tree) isn't working anymore due to some horrible SWT API stuff. How important is this feature?

**Comment by pinnecke** [comment] 2015-07-21 10:16
Please comment and reassign me afterwards.

**Comment by tthuem** [comment] 2015-07-21 10:42
The selection in the outline according to the diagram is quite important and vice versa is important for large projects.

**Comment by pinnecke** [comment] 2015-07-21 12:31
#### Current state

**Do not display invalid filters (hide fields...)** is *open*

Toolbar buttons/action can be removed and altered, if they are related to an identifier (IAction::setID(...)) and request by them. However, since the outline handles all different kinds of outline depending on the current labelProvider etc., figuring out the current state seems challenging. Therefore, hiding/showing buttons is challenging.

**Outline always collapes when chenging the focus** is *solved* but removed important feature.

The auto collapsing/auto expanding bug was a consequence of *autoExpand* behavior of the tree control whereas the selecting comes with clearing and reloading the tree. However, if one does not clear the tree, selecting an item seems painful due to it is not possible to traverse the tree without interactions with the UI nor it is possible to build some kind of index structure, that maps a feature to an reference to a related note in the tree.

Do you have some ideas here?

**Comment by pinnecke** [comment] 2015-07-21 12:31
See **remote branch 260**

**Comment by pinnecke** [comment] 2016-04-04 11:13
Buttons in the outline are always displayed and accessible independent of the context. This is fixed now and was caused by the method "showContextFieldsAndMethods" which always returned true independent of it is the ahead composer, feature composer, etc. I moved the decision whenever to show or hide context fields in the corresponding classes. However, in which contexts are these fields valid anyway? The current outline do not show fields etc., for Ahead, CPP, etc.

**Comment by pinnecke** [comment] 2016-04-11 14:08
Please review, and merge into develop-branch if it works for you.

**Comment by meinicke** [comment] 2016-04-14 09:09
Ho about hiding them instead of disable.
Do not show them for the feature model editor.

The rest seems to work and can be merged.

**Comment by pinnecke** [comment] 2016-04-20 08:51
merged.

**Closed by pinnecke** 2016-04-20 08:51 UTC
Labels: bug (major), Feature Modeling, In progress
