### ISSUE TITLE
Exception upon Deleting FeatureModel Root

### ISSUE THREAD

**Issue by Raixxor** [FeatureIDE/FeatureIDE#1083] opened 2020-09-29 15:10 UTC
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** release3.6 / 993824d28bd1252165753485654ae81773d43502

When deleting the root of a FeatureModel multiple exceptions are thrown. 

What happens is that all branches below the root except for one are deleted. 
If there is a constraint in any of the now disappeared branches the exceptions are thrown. However, if there are only constraints in the branch that remains, no exceptions are thrown.

**Comment by tthuem** [comment] 2020-10-12 13:01
@h3ssto Isn't this fixed?

**Comment by h3ssto** [comment] 2020-10-12 15:57
I could not reproduce this bug with v3.6.4.

**Comment by h3ssto** [comment] 2020-10-12 16:04
The issue is fixed by #1087.

**Closed by h3ssto** 2020-10-12 16:04 UTC
Labels: Feature Modeling, bug (major)
