### ISSUE TITLE
Default feature-model factory still used if customized factory is provided

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#374] opened 2016-07-20 06:42 UTC
#### Prerequisitives
* **Git branch/Commit-ID:**  develop, July 15

### Issue description
Reported from TU Wien: They created a custom factory for features. When loading an existing project, only the default factory is used (second part of the trace). For a new project, the custom factory is used, but not for feature "Base" (third part of the trace). 

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://3669.fwk2113171614:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://3669.fwk2113171614:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
!SESSION 2016-07-15 10:20:38.007 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_AT
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\rbeckert\workspace/../runtime-EclipseApplication(1) -dev file:C:/Users/rbeckert/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application (1)/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- ExtendedFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.ExtendedFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- RiskoptFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.RiskoptFeatureModelFactory ---XXX---
---XXX--- ExtendedFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.ExtendedFeatureModelFactory ---XXX---
---XXX--- RiskoptFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.RiskoptFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel(2params) ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= RiskOpttest2 ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= Base ---XXX---
---XXX--- FeatureModel: FeatureModel(2params) ---XXX---
---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel() ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= RiskOpttest2 ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= Base ---XXX---
---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel(2params) ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= RiskOptTest1 ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= Base ---XXX---
---XXX--- FeatureModel: FeatureModel(2params) ---XXX---

---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- ExtendedFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.ExtendedFeatureModelFactory ---XXX---
---XXX--- RiskoptFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.RiskoptFeatureModelFactory ---XXX---
---XXX--- RiskoptFeatureModelFactory: createFeatureModel() ---XXX---
---XXX--- RiskOptFeatureModelStructure: RiskOptFeatureModelStructure() ---XXX---
---XXX--- RiskOptFeatureModel: RiskOptFeatureModel() ---XXX---
---XXX--- RiskOptFeature: createProperty() ---XXX---
---XXX--- RiskOptFeature: createStructure() ---XXX---
---XXX--- RiskOptFeatureStructure: RiskOptFeatureStructure() ---XXX---
---XXX--- RiskOptFeature: RiskOptFeature(2params) name= RiskOptTest3 ---XXX---
---XXX--- RiskOptFeature: createProperty() ---XXX---
---XXX--- RiskOptFeature: createStructure() ---XXX---
---XXX--- RiskOptFeatureStructure: RiskOptFeatureStructure() ---XXX---
---XXX--- RiskOptFeature: RiskOptFeature(2params) name= Base ---XXX---
---XXX--- DefaultFeatureModelFactory: getId() ID= de.ovgu.featureide.fm.core.DefaultFeatureModelFactory ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel() ---XXX---
---XXX--- FeatureModel: FeatureModel(2params) ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= RiskOptTest3 ---XXX---
---XXX--- DefaultFeatureModelFactory: createFeature() Name= Base ---XXX---
´´´

**Comment by AlexanderKnueppel** [comment] 2016-08-05 06:56
I cannot reproduce this behaviour. If I add the following code to `de.ovgu.featureide.fm.core.FMCorePlugin.start(BundleContext context)`, I've successfully replaced the default factory:

```
FMFactoryManager.setDefaultFactory(RiskoptFeatureModelFactory.ID);
FMFactoryManager.factoryWorkspaceProvider.getFactoryWorkspace().setDefaultFactoryID(RiskoptFeatureModelFactory.ID);
```
If I remove the second line, the creation of feature models (`createFeatureModel()`) is performed by `DefaultFeatureModelFactory`, whereas all features (`createFeature(...)`) are created by the provided custom factory (is this intended?).

@tthuem Can you (or somebody else) more elaborate on the objective and the attempts to reach those? Simply replacing the default factory? Or do they have a specific feature model format, for which they want to use  `RiskoptFeatureModelFactory`?

**Comment by tthuem** [comment] 2016-08-18 15:44
Thanks Alex. Seems we need a minimal example from TU Wien to proceed.

**Comment by skrieter** [comment] 2016-08-24 11:03
Fixed in Branch [Core_Library](https://github.com/FeatureIDE/FeatureIDE/tree/Core_Library).
We plan to merge the branch at the end of September into develop.
Version 3.2.0 will include the bug fix.

**Closed** 2016-10-12 08:59 UTC
Labels: bug (major), Feature Modeling
