### ISSUE TITLE
Recently renamed features are put into the top left corner when opening the feature diagram in manual layout mode.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#725] opened 2018-03-19 16:41 UTC
1.  Select Manual Layout
2. Rename a feature
3. Save the diagram
4. Close the Feature Diagram Editor
5. Open the Feature Diagram Editor
6. The renamed feature is in the top left corner

This happens in both the develop and the release3.5 branch.

**Comment by tthuem** [comment] 2018-03-20 06:04
Sounds as the renaming is not applied to the graphical feature model.

**Comment by PaulWestphal** [comment] 2018-03-28 13:31
#408

**Comment by PaulWestphal** [comment] 2018-04-01 14:07
@Subaro review this please.

**Comment by tthuem** [comment] 2018-04-04 09:28
Why should the feature model be stored after every change? It should only be saved when the user requests the save. Seems to be wrong.

Unfortunately, the fix is already on develop. Please use a separate branch next time.

**Comment by Subaro** [comment] 2018-04-18 17:09
@PaulWestphal I found two problems that reference to this issue but not to directly to your fix.

Moving a feature does not make the feature model editor dirty:
1) Set manual layout.
2) Move a feature to another position.
3) Afterward, the editor is not set as dirty, but it should.

Features are not correctly loaded when opening a feature model:
1) Set Manual Layout 
2) Move feature "A" around
3) save the feature model (change a feature collapse status twice to force the dirty flag)
4) close and reopen the feature model
5) The feature "A" seems to be layout and is not moved to the position defined before.

**Comment by Subaro** [comment] 2018-04-18 19:59
We found out that the first problem:

"Moving a feature does not make the feature model editor dirty:"

is related to the issue #733 because the dirty flag does appear after the feature model was changed before. The problem is still open. For the second problem:

"Features are not correctly loaded when opening a feature model:"

is related to the issue #735 because the concurrent modification exception prevented the saving process for the graphical feature model. This problem is fixed with the commit bea8e5cb1e1aae0dbea5f3b26732a05c749d84ff.

**Closed** 2018-05-02 14:49 UTC
Labels: Feature Modeling, bug (minor)
