### ISSUE TITLE
Markers for inconsistent mappings do not work for Antenna

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#673] opened 2017-11-24 07:07 UTC
Markers for concrete features not used in the implementation are missing. However, the equivalent analysis for feature modules seems to be applied:

![feature-module-in-antenna](https://user-images.githubusercontent.com/5330357/33198926-3159b88c-d0ee-11e7-81d1-ef4ccebc9b48.png)

**Comment by tthuem** [comment] 2017-12-28 17:52
Markers do still not work and there are even more confusing markers now:

![unbenannt](https://user-images.githubusercontent.com/5330357/34418812-464844fc-ec00-11e7-84be-a22cdaf0b027.PNG)

**Comment by PaulWestphal** [comment] 2018-01-17 16:39
Markers for concrete features not used in the implementation seem to work for us.

**Comment by PaulWestphal** [comment] 2018-01-17 16:53
The marker appears when you change something in the code and then hit save.
![unbenannt](https://user-images.githubusercontent.com/32126695/35055261-0f7bb18e-fbaf-11e7-8c08-87d408d247b5.png)

**Comment by Kogoro** [comment] 2018-01-18 13:31
All markers, which are shown for elevator antenna v1.0 with fixed feature model:
![markers](https://user-images.githubusercontent.com/8019776/35100449-2325ae4e-fc5c-11e7-818c-a4a91b80697d.PNG)

**Comment by tthuem** [comment] 2018-01-18 18:42
Looks good except for three problems:

* "You should create a Feature [...]" should be completely banned from the code. The marker is rather confusing and the problem is already pointed out by the marker in source code.
* "False optional [...]" is duplicated
* "You should use the Feature" -> "The following features are marked concrete in the feature model but never referenced in the implementation: " rather use one problem marker instead of a separate one for each feature.

**Comment by PaulWestphal** [comment] 2018-01-23 16:20
I can't reproduce the duplicate false optional marker, but the other two problems are fixed.

**Comment by tthuem** [comment] 2018-01-23 18:04
@skrieter Please check whether it works now for our tutorial.

**Comment by skrieter** [comment] 2018-02-02 15:12
Fixed in release branch.

**Closed** 2018-02-02 17:39 UTC
Labels: Antenna, bug (major)
