### ISSUE TITLE
Create Feature Above with multiple features causes unexpected behaviour after undo

### ISSUE THREAD

**Issue by johannesherschel** [FeatureIDE/FeatureIDE#1313] opened 2021-10-26 21:43 UTC
* **Eclipse Version:** 4.17.0
* **FeatureIDE-Version:** 3.8
* **Operating system:** Ubuntu 20.04.2
* **Java runtime used to run eclipse:** openjdk 16.0.1

Create Feature Above used with multiple features causes errors in various cases. Example model:
![image](https://user-images.githubusercontent.com/84278649/138963426-cea08140-aabe-4416-9496-052c380186bd.png)

## Reversed feature order

When selecting "FeatureC", "FeatureB" and "FeatureA" (in that order), and then using Create Feature Above, the features are reordered:
![image](https://user-images.githubusercontent.com/84278649/138964065-443a1d58-7efe-45e4-97fc-bb723e538e44.png)

## Missing features

When selecting the features in the order "FeatureA", "FeatureB", "FeatureC", Create Feature Above does not change the feature order. However, when trying to undo the operation, some features are lost:
![image](https://user-images.githubusercontent.com/84278649/138964514-c233dbeb-9090-49b8-aede-2b8b38a6c363.png)

With different models and selection orders, there are also cases where features are both reordered and falsely deleted when using undo, e.g. when selecting the features in the order "FeatureA", "FeatureC", "FeatureB" in the above example.

**Comment by Rahel12342** [comment] 2021-11-15 11:52
I am not able to reproduce the changing of the feature order. 
However, when undoing the operation, the features 'FeatureA' and 'FeatureB' are disappearing for me, too.

**Comment by skrieter** [comment] 2023-03-25 19:26
Fixed in 72dbfd6afd14f5ca10d2f835546cf261f437d68d

**Closed** 2023-03-25 19:25 UTC
Labels: bug (minor), Feature Modeling
