### ISSUE TITLE
Annotation Warning does not work 

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#269] opened 2015-06-18 10:14 UTC
if there is a whitespace after // the warning mechanism (e.g., for tautologies) does not work anymore.
![markerantennadefect](https://cloud.githubusercontent.com/assets/1482595/8228999/80f61cb2-15b3-11e5-94ce-a520d697662e.PNG)

**Comment by pinnecke** [comment] 2016-04-20 08:54
Did it work in a previous version, or is this information not available?

**Comment by pinnecke** [comment] 2016-04-20 09:01
Can not reproduce the issue. Might be fixed by another fix. See screenshots below, check again if you can reproduce the issue. If not, close the issue. Otherwise give a minimal but complete example when the problem occurs.

![bildschirmfoto 2016-04-20 um 10 59 59](https://cloud.githubusercontent.com/assets/3775170/14669027/4021542e-06e7-11e6-879b-964a0b8d848a.png)
![bildschirmfoto 2016-04-20 um 11 00 04](https://cloud.githubusercontent.com/assets/3775170/14669028/40444da8-06e7-11e6-97e7-7d3d0dec087e.png)

**Comment by meinicke** [comment] 2016-04-20 13:06
read the issue

"if there is a whitespace after // the warning mechanism (e.g., for tautologies) does not work anymore."

**Comment by pinnecke** [comment] 2016-04-20 13:31
explain the problem correct.

A minimal example is (see attachment)? Correct? The problem does not occur if I follow your description. 

One has to change the active configuration since refreshing seems broken. 

I reproduced it as follows:

- Take the HelloWorld Antenna Example
- Transform the Model as done in the description (see attachment)
- Open Main.java in the src folder
- Introduce a whitespace such that the code is as follows (please note the „ " after the // and before the #if

		public class Main {

	public static void main(String[] args){
		//#if Hello
		System.out.print("Hello");
		//#endif
		
		// #if World
		System.out.print(" world!");
		//#endif
	}


- Close the Main.java file
- Change to another active configuration (e.g., WonderfulWorld.config)
- Reopen Main.java file
-> The marker is gone but should be there indicating #if World is a tautology

Thats a description to the problem one can follow to reproduce the issue.
Now I’m able to see the problem. 

Yes, it is still open.

**Comment by tthuem** [comment] 2016-06-21 19:46
This is something that we want to heavily rely on for the SPLC tutorial.

@pinnecke Could you please try to fix that?

**Comment by Kogoro** [comment] 2016-07-04 21:19
The problem still exists in the latest nightly build. To solve it, I think every contains must be checked in [AntennaPreprocessor.java](https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.core.antenna/src/de/ovgu/featureide/antenna/AntennaPreprocessor.java). In [AntennaModelBuilder.java](https://github.com/FeatureIDE/FeatureIDE/blob/develop/plugins/de.ovgu.featureide.core.antenna/src/de/ovgu/featureide/antenna/model/AntennaModelBuilder.java), it is already solved through adding `\s*` to the pattern.

**Comment by Kogoro** [comment] 2016-07-13 20:37
Should work now also with whitespaces between // and #.
Maybe someone can verify the change, before merging into develop.

**Comment by tthuem** [comment] 2016-07-13 20:47
Marcus, can you review the fix?

**Comment by tthuem** [comment] 2016-07-13 20:52
Jens, can you review the fix as Marcus is not available?

**Closed** 2016-07-13 21:05 UTC
Labels: Antenna, bug (major), In review
