### ISSUE TITLE
Improve support for #condition in Antenna projects

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#352] opened 2016-05-11 09:20 UTC
#### Prerequisitives
- **FeatureIDE Composer:** Antenna
### Issue description

Antenna allows to exclude complete files using #condition FEATURE
Currently the build process works, but not any additional support (colors, line numbers(should be all), analyses (e.g., dead code))

**Comment by meinicke** [comment] 2016-05-17 10:40
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/e39a912eb2262a792f4689bade2c265efd5d97b3

**Comment by tthuem** [comment] 2016-05-19 17:21
We experienced a case were a condition is missing in the collaboration diagram. Reimar can give more details in the next days.

**Comment by tthuem** [comment] 2016-06-21 19:07
Reimar, we need your input for that.

**Comment by RSchroeter** [comment] 2016-07-13 12:32
The problem occurs if multiple classes exist in one file. The case is simply not yet supported .

**Comment by tthuem** [comment] 2016-07-13 12:33
Hence, a possible task for a software project?

**Comment by RSchroeter** [comment] 2016-07-13 12:39
Yes, why not? 

I found a second error with the same result. If a file name is a prefix of another file name, only one class is represented in the diagram.

**Comment by skrieter** [comment] 2018-09-06 13:53
Could not reproduce. Seems to be fixed in the meantime.

**Closed by skrieter** 2018-09-06 13:53 UTC
Labels: Antenna, bug (minor)
